# Generated by Django 4.2.6 on 2023-10-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_customer_profile_picture_seller_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='company_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
